import type { Metadata } from "next";
import { ChakraProvider } from "@chakra-ui/react";
import { AuthProvider } from "./_Auth/AuthContext";

export const metadata: Metadata = {
  title: "Personal expense tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <ChakraProvider>{children}</ChakraProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
